version: "1"
services:
  web:
    image: centos:7
    expose:
      - "8000/tcp"
    ports:
      - "80:80"
      - "8000:8000"
    links:
      - redis:redis
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - LOGGING=True
      - SECRET_KEY={{ lookup('credstash', 'sso-dashboard.secret_key', region='us-east-1', app='sso-dashboard') }}
      - ENVIRONMENT=Production
      - OIDC_DOMAIN={{ lookup('credstash', 'sso-dashboard.oidc_domain', region='us-east-1', app='sso-dashboard') }}
      - OIDC_CLIENT_ID={{ lookup('credstash', 'sso-dashboard.oidc_client_id', region='us-east-1', app='sso-dashboard') }}
      - OIDC_CLIENT_SECRET={{ lookup('credstash', 'sso-dashboard.oidc_client_secret', region='us-east-1', app='sso-dashboard') }}
      - SERVER_NAME={{ lookup('credstash', 'sso-dashboard.server_name', region='us-east-1', app='sso-dashboard') }}
      - PERMANENT_SESSION=86400
      - PERMANENT_SESSION_LIFETIME=86400
      - REDIS_URL=redis://redis:6379
      - S3_BUCKET={{ lookup('credstash', 'sso-dashboard.s3_bucket', region='us-east-1', app='sso-dashboard') }}
      - MOZILLIANS_API_URL=https://mozillians.org/api/v2/users/
      - MOZILLIANS_API_KEY={{ lookup('credstash', 'sso-dashboard.mozillians_api_key', region='us-east-1', app='sso-dashboard') }}
      - DEFAULT_AVATAR=/static/img/user.svg
    working_dir: '/sso-dashboard'
    command: ['/usr/bin/dumb-init', '/usr/bin/start.sh']
    dev_overrides:
      environment:
        - AWS_DEFAULT_REGION=us-west-2
        - LOGGING=True
        - ENVIRONMENT=Development
        - SERVER_NAME=localhost:8000
        - S3_BUCKET=sso-dashboard.configuration
        - SECRET_KEY={{ lookup('credstash', 'sso-dashboard.secret_key', region='us-east-1', app='sso-dashboard') }}
        - OIDC_DOMAIN={{ lookup('credstash', 'sso-dashboard.oidc_domain', region='us-east-1', app='sso-dashboard') }}
        - OIDC_CLIENT_ID={{ lookup('credstash', 'sso-dashboard.oidc_client_id', region='us-east-1', app='sso-dashboard') }}
        - OIDC_CLIENT_SECRET={{ lookup('credstash', 'sso-dashboard.oidc_client_secret', region='us-east-1', app='sso-dashboard') }}
        - PERMANENT_SESSION=600
        - PERMANENT_SESSION_LIFETIME=900
        - REDIS_URL=redis://redis:6379
        - MOZILLIANS_API_URL=https://mozillians.org/api/v2/users/
        - MOZILLIANS_API_KEY={{ lookup('credstash', 'sso-dashboard.mozillians_api_key', region='us-east-1', app='sso-dashboard') }}
        - DEFAULT_AVATAR=/static/img/user.svg
  redis:
    image: redis
    expose:
      - "6379/tcp"
    ports:
      - "6379:6379"
    command: ['redis-server']
registries: {}
